query PrivyTrade($hash: String!, $block: Block_height) {
  _meta(block: $block) {
    block {
      number
      hash
      timestamp
    }
    hasIndexingErrors
    deployment
  }
  swaps(block: $block, where: { hash: $hash }) {
    id
    hash
    logIndex
    blockNumber
    timestamp
    amountIn
    amountOut
    tokenIn {
      id
      symbol
      decimals
    }
    tokenOut {
      id
      symbol
      decimals
    }
    pool {
      id
      feeBasisToken {
        id
        symbol
      }
    }
  }
  hookFeeAccruals(block: $block, where: { hash: $hash }) {
    id
    hash
    logIndex
    blockNumber
    timestamp
    trader
    wethVolume
    feesWeth
    rewardsWeth
    liquidityWeth
    creatorWeth
  }
}
