query StandardMarket($block: Block_height) {
  _meta(block: $block) {
    block {
      number
      hash
      timestamp
    }
    hasIndexingErrors
    deployment
  }
  dexAmmProtocols(first: 1, block: $block) {
    id
    name
    schemaVersion
    network
    cumulativeUniqueUsers
    totalValueLockedUSD
  }
  liquidityPools(
    block: $block
    first: 1
    orderBy: createdTimestamp
    orderDirection: asc
  ) {
    id
    inputTokens {
      id
      name
      symbol
      decimals
    }
    swaps(first: 3, orderBy: timestamp, orderDirection: desc) {
      hash
      timestamp
      tokenIn {
        symbol
        decimals
      }
      amountIn
      tokenOut {
        symbol
        decimals
      }
      amountOut
    }
  }
}
