import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  decodeConfiguredDeploymentSelection,
  configuredDeploymentEnvironments,
} from "@orbit/config/deployment-environments";
import { decodeProtocolDeploymentManifest } from "@orbit/config/deployment-manifest";
import { Effect } from "effect";
import { format } from "prettier";

import { ensure, fileSystem, runMain, validate } from "./effect-runtime.ts";

runMain(
  Effect.gen(function* () {
    const repositoryRoot = dirname(dirname(fileURLToPath(import.meta.url)));
    const outputPath = join(
      repositoryRoot,
      "apps/web/src/generated/deployment-manifests.ts",
    );
    const bindings = yield* Effect.forEach(
      configuredDeploymentEnvironments,
      (environment) =>
        Effect.gen(function* () {
          const sourcePath = join(repositoryRoot, environment.manifestPath);
          const source = yield* fileSystem(
            `Could not read the ${environment.name} deployment manifest`,
            () => readFileSync(sourcePath, "utf8"),
          );
          const manifest = yield* validate(
            `${environment.name} deployment manifest is invalid`,
            () =>
              decodeProtocolDeploymentManifest(JSON.parse(source) as unknown),
          );
          yield* validate(
            `${environment.name} deployment manifest does not match its environment`,
            () =>
              decodeConfiguredDeploymentSelection({ environment, manifest }),
          );
          return {
            digest: createHash("sha256").update(source).digest("hex"),
            environment,
            manifest,
          };
        }),
    );
    const sourceComments = bindings
      .map(
        ({ digest, environment }) =>
          `// ${environment.name}: ${environment.manifestPath} (SHA-256 ${digest})`,
      )
      .join("\n");
    const manifestEntries = Object.fromEntries(
      bindings.map(({ environment, manifest }) => [environment.name, manifest]),
    );
    const generated = yield* Effect.tryPromise({
      try: () =>
        format(
          `// Generated by scripts/generate-web-deployment-manifest.ts.\n${sourceComments}\nimport type { ConfiguredDeploymentEnvironment } from "@orbit/config/deployment-environments";\nimport type { ProtocolDeploymentManifest } from "@orbit/config/deployment-manifest";\n\ntype ConfiguredEnvironmentName = ConfiguredDeploymentEnvironment["name"];\n\nexport const protocolDeploymentManifests = ${JSON.stringify(manifestEntries, null, 2)} as const satisfies Readonly<Record<ConfiguredEnvironmentName, ProtocolDeploymentManifest>>;\n`,
          { parser: "typescript" },
        ),
      catch: (cause) =>
        new Error("Could not format the generated binding", { cause }),
    });

    const existingOutput = yield* fileSystem(
      "Could not inspect the generated web deployment binding",
      () =>
        existsSync(outputPath) ? readFileSync(outputPath, "utf8") : undefined,
    );

    if (process.argv.includes("--check")) {
      yield* ensure(
        existingOutput === generated,
        "The web deployment bindings are stale; run pnpm generate:web-deployment-manifest",
      );
      process.stdout.write(
        "Web deployment bindings match the checked manifests\n",
      );
    } else {
      yield* fileSystem("Could not write the web deployment binding", () => {
        mkdirSync(dirname(outputPath), { recursive: true });
        writeFileSync(outputPath, generated);
      });
      process.stdout.write(`Generated ${outputPath}\n`);
    }
  }),
);
